### PR TITLE
Support new OS distro Ubuntu 19.10 (Eoan).

### PR DESCRIPTION
**Pull request by jkschulz**

### CODE REVIEW

**Comment by igorpeshansky** [comment]
Is this a replacement for #87? How is this different?

**Comment by jkschulz** [comment]
I ended up on another branch so this one replaces that and also adds the control file and rules file update.

**Comment by qingling128** [comment]
Compared this with Bionic (Ubuntu 1804). Looks almost identical except some minor lib version bump. LGTM'd.

**Comment by StevenYCChou** [comment]
> Compared this with Bionic (Ubuntu 1804). Looks almost identical except some minor lib version bump. LGTM'd.

LGTM too for the same reason. Couldn't think of anything on top of my head needs to be added.

**Pull request merged**
