### PR TITLE
Add Dockerfile for Ubuntu 18.04 build container

### PR DESCRIPTION
**Pull request by gbprz**
Adds the Dockerfile for an Ubuntu 18.04 build container.

### CODE REVIEW

**Comment by gbprz** [comment]
@igorpeshansky rebased to dhrupadb-build-dockerfiles and changed the PR to merge into dhrupadb-build-dockerfiles as well as discussed. Please let me know if there is anything else I can do for this.

**Comment by qingling128** [comment]
FYI, https://github.com/Stackdriver/agent-packaging/pull/3 has been merged. Please point the base branch at `stackdriver-agent-5.5.2` instead. Might need to rebase if necessary.

**Comment by gbprz** [comment]
This should be all set now, let me know if there is anything else I can do.

**Comment by igorpeshansky** [comment]
Next time, let's squash-and-merge, please.

**Comment by igorpeshansky** [comment]
FYI, I've rebased stackdriver-agent-5.5.2 to remove the merge commit.

**Comment by thvd** [comment]
Does this PR mean the agent is ready to be installed on Ubuntu 18.04? I still get this error: 
```

E: The repository 'http://packages.cloud.google.com/apt google-cloud-monitoring-bionic Release' does not have a Release file.
Could not update apt repositories.
Please check your network connectivity and
make sure you are running a supported Ubuntu/Debian distribution.
See https://cloud.google.com/monitoring/agent/#supported_operating_systems for a list of supported platforms.


```

**Comment by qingling128** [comment]
@thvd - This PR is a prerequisite to support building the package from Ubuntu 18.04. We have not yet released a formal package yet. Still testing it. There is no formal timeline yet, but we are actively working on it.

**Pull request merged**
